name: lint

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run:
          npx prettier . --check
          # linting results in 743 errors, only 160 of which can be auto-fixed.
          # Let's leave this check aside for now.
          # npm run lint
